### ISSUE TITLE
December 2023 task list

### ISSUE THREAD

**Issue by ChloeRN** [ErlendNilsen/OpenPop_Integrated_DistSamp#34]
Below is an overview of the tasks that need doing for submitting the two manuscripts in the end of 2023. 

**Manuscript 1 (model presentation)**

- [ ] Add missing files (results plots)
- [ ] Complete first draft for manuscript 1

**Manuscript 2 (multi-area workflow)**

- [ ] Recruit someone to make maps pretty
- [ ] Plan out writing of second manuscript

**Code**

- [ ] Complete and test new model setup
- [ ] Do a full run of multi-area setup
- [ ] Write code for new visualizations for multi-area results
